/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.ahm.mo.mst.app351.constant;

/**
 *
 * @author patria
 */
public class Mst351Constant {
    public static final String Lov_Storage_Loc = "SELECT VITEMCODE, VITEMDESC, VITEMNAME FROM ahmmoerp_dtlsettings where rset_vid = 'MSTSLOCSHIPPING'";
    
    public static final String Count_Storage_Loc ="SELECT VITEMCODE, VITEMDESC, VITEMNAME FROM ahmmoerp_dtlsettings  WHERE rset_vid = 'MSTSLOCSHIPPING' and VITEMCODE= :VITEMCODE";
    
    public static final String Data_Shipping_No = "select ishipno, to_char(dshipact,'dd-MON-yyyy hh24:mi:ss')dshipact,(xxquetr_xabstr_mtruck_vareapol || ' ' || x1xquetr_xabstr_mtruck_vnumpol || ' ' || x1xquetr_xabstr_mtruck_vpempol) truckno,vnodo, vexpdesc, mstor_mplant_vplantid, ishipyear, CSAREA_ID_CSAREA from ahmmomst_hdrshpfuds, ahmmomst_mstexpds, fmppc_pc00_delords where DO_NO = VNODO And (Xquexabstr_Mtruck_Mexpd_Vexpid = Vexpid(+)) And Ishipyear = :ISHIPYEAR And Mstor_Vslocid = :VSLOCID and mstor_mplant_vplantid = :VPLANID and mstats_dset_rset_vid = 'MSTSTATSHPLIST' And Mstats_Dset_Vitemcode = '1' Order By Mstor_Mplant_Vplantid, Ishipyear, Ishipno" ;

    public static final String Data_Hdr_Shipping = "SELECT MPACK_VITEMCODE,MPACK_RSET_VID,ISHIPNO,ISHIPYEAR,DSHIPACT,DSHIPPOST,VNODO,ISHIPQTY,DSHIPPROC,MSTOR_MPLANT_VPLANTID,MSTOR_VSLOCID,X1XQUETR_XABSTR_MTRUCK_VPEMPOL,X1XQUETR_XABSTR_MTRUCK_VNUMPOL,X1ALTR_MGTSHP_VGATEID,XXQUETR_XABSTR_MPLANT_VPLANTID,XQUEXABSTR_MTRUCK_MEXPD_VEXPID,XXQUETR_XABSTR_MTRUCK_VAREAPOL,X1ALTR_MGTSHP_ILANTAI,X1ALTR_XQUETR_XABSTR_DDTABSEN,X1ALTR_XQUETR_XABSTR_ISEQ,MSTATS_DSET_RSET_VID,MSTATS_DSET_VITEMCODE,XQUETR_XABSTR_MTRUCK_MCATEG_VT,Xquetr_Xabstr_Mtruck_Mcateg_Id FROM Ahmmomst_Hdrshpfuds WHERE Ishipno             = :ISHIPNO  AND Ishipyear             = :ISHIPYEAR  AND Mstor_Mplant_Vplantid = :VPLANTID AND MSTOR_VSLOCID         = :VSLOCID";

    public static final String Data_Shipping_List = "SELECT hdr.DSHIPACT,hdr.XXQUETR_XABSTR_MTRUCK_VAREAPOL|| ' '|| hdr.X1XQUETR_XABSTR_MTRUCK_VNUMPOL|| ' '|| Hdr.X1xquetr_Xabstr_Mtruck_Vpempol Nomorpolisi,Exp.Vexpdesc AS Vexpdesc,Hdr.Vnodo AS Vnodo,Vnd.Vnd_Name AS Vnd_Name,Scnfud.Meng_Vengno AS Meng_Vengno,Scnfud.Mframe_Vfrmno AS Mframe_Vfrmno,Scnfud.Dshfud_Mtpcol_Rtype_Vmctypeid AS Dshfud_Mtpcol_Rtype_Vmctypeid,scnfud.DSHFUD_MTPCOL_MCOL_VCOLORID   AS DSHFUD_MTPCOL_MCOL_VCOLORID,DSET_VITEMCODE_DPKCODE FROM ahmmomst_txnscanfuds scnfud,ahmmomst_hdrshpfuds hdr,ahmmomst_mstexpds exp,fmppc_pc00_delords sipb,fmppc_pp00_vendors vnd,ahmmosfc_mst1frames frame WHERE scnfud.MFRAME_VFRMNO = frame.VFRMNO AND scnfud.DSHFUD_RSHPFUD_ISHIPNO         = hdr.ISHIPNO AND scnfud.DRSHPFUD_MSTOR_MPLANT_VPLANTID = hdr.MSTOR_MPLANT_VPLANTID AND scnfud.DSHFUD_RSHPFUD_ISHIPYEAR       = hdr.ISHIPYEAR AND scnfud.DSHFUD_RSHPFUD_MSTOR_VSLOCID   = hdr.MSTOR_VSLOCID AND vnd.VNDTYP_VND_TYPE                   = sipb.VEND_VNDTYP_VND_TYPE_DEALER AND vnd.VND_CODE                          = sipb.VEND_VND_CODE_DEALER AND (hdr.XQUEXABSTR_MTRUCK_MEXPD_VEXPID   = exp.VEXPID(+)) AND Sipb.Do_No                            = Hdr.Vnodo AND Hdr.Ishipyear                         = :ISHIPYEAR AND Hdr.Ishipno                           = :ISHIPNO AND Hdr.Mstor_Vslocid                     = :VSLOCID  AND hdr.MSTOR_MPLANT_VPLANTID             = :VPLANTID";

    public static final String Data_Acc = "select DSHFUD_MTPCOL_RTYPE_VMCTYPEID VMCTYPEID,DSHFUD_MTPCOL_MCOL_VCOLORID VCOLORID,count(scnfud.MENG_VENGNO) QTYSHIP,scnfud.DRSHPFUD_MSTOR_MPLANT_VPLANTID VPLANTID,hdr.ISHIPNO ISHIPNO, hdr.ISHIPYEAR ISHIPYEAR from ahmmomst_txnscanfuds scnfud,ahmmomst_hdrshpfuds hdr,ahmmosfc_mst1frames frame where scnfud.MFRAME_VFRMNO = frame.VFRMNO and scnfud.DSHFUD_RSHPFUD_ISHIPNO = hdr.ISHIPNO and scnfud.DRSHPFUD_MSTOR_MPLANT_VPLANTID = hdr.MSTOR_MPLANT_VPLANTID and scnfud.DSHFUD_RSHPFUD_ISHIPYEAR = hdr.ISHIPYEAR and scnfud.DSHFUD_RSHPFUD_MSTOR_VSLOCID = hdr.MSTOR_VSLOCID and hdr.ISHIPYEAR = :ISHIPYEAR and hdr.ISHIPNO = :ISHIPNO and hdr.MSTOR_VSLOCID = :VSLOCID And Hdr.Mstor_Mplant_Vplantid = :VPLANTID group by (scnfud.DSHFUD_MTPCOL_RTYPE_VMCTYPEID, scnfud.DSHFUD_MTPCOL_MCOL_VCOLORID, scnfud.DRSHPFUD_MSTOR_MPLANT_VPLANTID,hdr.ISHIPYEAR,hdr.ISHIPNO)";

    public static final String Count_BOM_Acc = "SELECT count(1) VDUMMY FROM AHMMOERP_DTLSETTINGS WHERE RSET_VID = 'MSTVCHACCSWITHBOMACC'   AND VITEMCODE = 'MSTVCHACCSWITHBOMACC'   AND BVALID = 'T' ";

    public static final String Data_Dtl_Acc = "select VPARTNUM, VPARTDESC, NQTYUSE, VMCTYPEID, VCOLORID, VPLANTID,(to_number(NQTY) * NQTYUSE) NQTY from ((Select  Distinct Mpart_Vpartnum Vpartnum, Vpartdesc, Nqtypunit Nqtyuse, H.Rtype_Vmctypeid Vmctypeid, H.Mcol_Vcolorid Vcolorid,h.MPLANT_VPLANTID VPLANTID,:JUMLAH NQTY from ahmmomsc_mstbomords b, ahmmomsc_mstlines l, ahmmomsc_dtlmlayouts d, ahmmomsc_hdrmlayouts h, ahmmomsc_mstparts p where d.RMLAY_VMLAYOUTID = h.VMLAYOUTID and d.RMLAY_MPLANT_VPLANTID = h.MPLANT_VPLANTID  and b.MLINES_VLINEID = l.VLINEID  and b.MPART_VPARTNUM = d.DSPL_MPART_VPARTNUM_CHILD and b.MPART_VPARTNUM = p.VPARTNUM and b.MTPCOL_RTYPE_VMCTYPEID = h.RTYPE_VMCTYPEID and b.MTPCOL_MCOL_VCOLORID = h.MCOL_VCOLORID And L.Mplant_Vplantid = H.Mplant_Vplantid And B.Mtpcol_Rtype_Vmctypeid = :TYPEID And B.Mtpcol_Mcol_Vcolorid = :COLORID And L.Mplant_Vplantid = :PLANTID and d.BFLAGACCS = 'T' and h.BFLRELEASE = 'T' and d.BFLAGZL = 'F') union  (select a.MPART_VPARTNUM VPARTNUM, VPARTDESC, a.NQTYUSING NQTYUSE, A.Mtpcol_Rtype_Vmctypeid Vmctypeid, A.Mtpcol_Mcol_Vcolorid Vcolorid,a.MPLANT_VPLANTID VPLANTID,:JUMLAH1 NQTY from ahmmomsc_mstaccsstds a, ahmmomsc_mstparts p Where A.Mpart_Vpartnum = P.Vpartnum  And a.MTPCOL_RTYPE_VMCTYPEID = :TYPEID1 And a.MTPCOL_MCOL_VCOLORID = :COLORID1 and a.MPLANT_VPLANTID = :PLANTID1 and sysdate between a.dbegineff and a.dendeff))";

    public static final String Data_Dtl_Acc1 = "SELECT DISTINCT MPART_VPARTNUM VPARTNUM, VPARTDESC, NQTY NQTYUSE, (to_number(:JUMLAH) * NQTY) NQTY FROM AHMMOMSC_HDRBOMACCS HDR, AHMMOMSC_DTLBOMACCS DTL,     AHMMOMSC_MSTPARTS P  WHERE DTL.RBACC_VBOMID = HDR.VBOMID    AND DTL.MPART_VPARTNUM = P.VPARTNUM    AND RMLAY_MPLANT_VPLANTID = :PLANTID    AND MTPCOL_RTYPE_VMCTYPEID = :TYPEID    AND MTPCOL_MCOL_VCOLORID = :COLORID    AND SYSDATE BETWEEN HDR.DBEGINEFF AND HDR.DENDEFF    AND SYSDATE BETWEEN P.DBEGINEFF AND P.DENDEFF";

    public static final String Data_Dtl_Acc2 = "SELECT DISTINCT MPART_VPARTNUM VPARTNUM, VPARTDESC, NQTY NQTYUSE, (to_number(:JUMLAH) * NQTY) NQTY FROM AHMMOMSC_HDRBOMACCS HDR, AHMMOMSC_DTLBOMACCS DTL,     AHMMOMSC_MSTPARTS P  WHERE DTL.RBACC_VBOMID = HDR.VBOMID    AND DTL.MPART_VPARTNUM = P.VPARTNUM    AND MTPCOL_RTYPE_VMCTYPEID = :TYPEID    AND MTPCOL_MCOL_VCOLORID = :COLORID    AND SYSDATE BETWEEN HDR.DBEGINEFF AND HDR.DENDEFF    AND SYSDATE BETWEEN P.DBEGINEFF AND P.DENDEFF";

    public static final String Data_Report = "SELECT VITEMNAME, VITEMDESC FROM AHMMOERP_DTLSETTINGS   where RSET_VID =  '_SERVER_SETTING' AND VITEMCODE = 'HOST_11G_REPD'";

    public static final String Data_Report2 = "SELECT VITEMNAME, VITEMDESC FROM AHMMOERP_DTLSETTINGS   where RSET_VID = '_SERVER_SETTING' AND VITEMCODE = 'REPORT_APP_11GD'";

    public static final String Cek_No_Ship = "select ishipno, to_char(dshipact,'dd-MON-yyyy hh24:mi:ss')dshipact,(xxquetr_xabstr_mtruck_vareapol || ' ' || x1xquetr_xabstr_mtruck_vnumpol || ' ' || x1xquetr_xabstr_mtruck_vpempol) truckno, vnodo, vexpdesc, mstor_mplant_vplantid, ishipyear, CSAREA_ID_CSAREA from ahmmomst_hdrshpfuds, ahmmomst_mstexpds, fmppc_pc00_delords where DO_NO = VNODO And (Xquexabstr_Mtruck_Mexpd_Vexpid = Vexpid(+)) And Ishipyear = :ISHIPYEAR  And Mstor_Vslocid = :VSLOCID  and mstor_mplant_vplantid = :VPLANTID  and mstats_dset_rset_vid = 'MSTSTATSHPLIST' And Mstats_Dset_Vitemcode = '1'  and ishipno= :ISHIPNO  Order By Mstor_Mplant_Vplantid, Ishipyear, Ishipno";
}
